server:
        port: 8080

        spring:
        datasource:
        url: jdbc:postgresql://localhost:5432/mcp
        username: postgres
        password: postgres
        jpa:
        hibernate:
        ddl-auto: update
        elasticsearch:
        uris: http://localhost:9200
        cache:
        type: redis
        redis:
        time-to-live: 60000